In [1]:
import numpy as np


In [5]:
x=np.array([5,7,3])
x2d=np.array([[1,2,3],[4,5,6]])
x3d= np.array([[[1,3],[4,2]],[[2,1],[3,4]]])
print(x)
print(x2d)
print(x3d)

[5 7 3]
[[1 2 3]
 [4 5 6]]
[[[1 3]
  [4 2]]

 [[2 1]
  [3 4]]]


In [12]:
#sequential matrix, np.arange() and np.Linspace()
np.arange(0,10, .2).size


50

In [13]:
np.arange(0,10, .2).reshape(5,10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [15]:
# Linspace() #divides in number of parts mentioned
np.linspace(0,15,100)

array([ 0.        ,  0.15151515,  0.3030303 ,  0.45454545,  0.60606061,
        0.75757576,  0.90909091,  1.06060606,  1.21212121,  1.36363636,
        1.51515152,  1.66666667,  1.81818182,  1.96969697,  2.12121212,
        2.27272727,  2.42424242,  2.57575758,  2.72727273,  2.87878788,
        3.03030303,  3.18181818,  3.33333333,  3.48484848,  3.63636364,
        3.78787879,  3.93939394,  4.09090909,  4.24242424,  4.39393939,
        4.54545455,  4.6969697 ,  4.84848485,  5.        ,  5.15151515,
        5.3030303 ,  5.45454545,  5.60606061,  5.75757576,  5.90909091,
        6.06060606,  6.21212121,  6.36363636,  6.51515152,  6.66666667,
        6.81818182,  6.96969697,  7.12121212,  7.27272727,  7.42424242,
        7.57575758,  7.72727273,  7.87878788,  8.03030303,  8.18181818,
        8.33333333,  8.48484848,  8.63636364,  8.78787879,  8.93939394,
        9.09090909,  9.24242424,  9.39393939,  9.54545455,  9.6969697 ,
        9.84848485, 10.        , 10.15151515, 10.3030303 , 10.45

In [19]:
np.linspace(0,10,5).reshape(5,1)

array([[ 0. ],
       [ 2.5],
       [ 5. ],
       [ 7.5],
       [10. ]])

In [20]:
#randomized matrix with np.random
#np.random.rand()
print(np.random.rand(2,2)) #0 to 1

[[0.00356452 0.67752708]
 [0.80618679 0.33545319]]


In [21]:
# np.random.randn() normal distribution
print(np.random.randn(3,3))

[[-1.5056184   0.58044059  0.48278372]
 [ 0.82389263 -0.69850101 -0.65745565]
 [-0.35947376  1.32844399 -0.36292283]]


In [22]:
#np.random.randint()
print(np.random.randint(-10,10,(3,3))) # random int from -10 to 10


[[ -1  -3   4]
 [  6   1  -7]
 [ -4 -10   4]]


In [27]:
#np.random.uniform()
print(np.random.uniform(0,2,(3,3))) 

[[1.02147991 0.854873   0.46316738]
 [1.75380303 0.13816297 0.26779453]
 [0.82753724 1.34542562 1.91089943]]


In [28]:
#np.random.permutation()
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10]))

[ 5  2  3  7  8  4  9  6  1 10]


In [ ]:
xp=

# operations 

In [29]:
a= np.random.randint(-10,10,(3,3))
b= np.random.randint(-10,10,(3,3))
print(a)
print(b)

[[ -4 -10   8]
 [ -5   8  -9]
 [  0  -3   2]]
[[ 6  6 -8]
 [ 2 -5  4]
 [ 2 -4  7]]


In [30]:
# matrix and constant operations
a*10

array([[ -40, -100,   80],
       [ -50,   80,  -90],
       [   0,  -30,   20]])

In [31]:
a%10

array([[6, 0, 8],
       [5, 8, 1],
       [0, 7, 2]], dtype=int32)

In [32]:
a**2

array([[ 16, 100,  64],
       [ 25,  64,  81],
       [  0,   9,   4]])

In [34]:
# same size matrix operations 
print(a +b)
print(a -b)
print(a /b)
print(a *b)


[[ 2 -4  0]
 [-3  3 -5]
 [ 2 -7  9]]
[[-10 -16  16]
 [ -7  13 -13]
 [ -2   1  -5]]
[[-0.66666667 -1.66666667 -1.        ]
 [-2.5        -1.6        -2.25      ]
 [ 0.          0.75        0.28571429]]
[[-24 -60 -64]
 [-10 -40 -36]
 [  0  12  14]]


In [35]:
print(a @ b) # matrix multiplication

[[-28  -6  48]
 [-32 -34   9]
 [ -2   7   2]]


In [36]:
np.matmul(a,b)

array([[-28,  -6,  48],
       [-32, -34,   9],
       [ -2,   7,   2]])