In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
type(x)

[1 2 3 4 5]


numpy.ndarray

In [4]:
# we can also pass a list, tuple or any array  like object with array() and it will be converted to ndarray
a= np.array((7,9,9,1,4,3))
print(a)

[7 9 9 1 4 3]


In [6]:
# dimensions in array - a dimension in array is one level of array depth(nested array)

# 0-D Array  -   scalars, are the elements in an array, each value in an array is a O-D array

# O-D array with value 42
y=np.array(42)
print(y)

42


In [7]:
#1-D array - an array that has 0-D arrays as its elements is uni directional or 1-D
one_d=np.array([11,12,13,14,15])
print(one_d)

[11 12 13 14 15]


In [9]:
# 2-D array
two_d=np.array([[1,2,3],[6,7,8]])
print(two_d)

[[1 2 3]
 [6 7 8]]


In [25]:
# 3-D array created with two 2-D array
three_d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(three_d)
print(three_d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [11]:
print(a.ndim)
print(x.ndim)
print(y.ndim)
print(one_d.ndim)
print(two_d.ndim)
print(three_d.ndim)

1
1
0
1
2
3


In [12]:
# 5-D array conversion to 1 D 
five_d=np.array([1,2,3,4,5], ndmin=5)
print(five_d)
print("number of dimensions:", five_d.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


# indexing

In [19]:
# array indexing is same as accessing an array element 
# starts from 0 to n
ind=np.array([11,12,13,14])
print(ind[1],ind[2],ind[0])

12 13 11


In [17]:
# we can get element from adding them
ind=np.array([11,12,13,14])
print(ind[2]+ind[3])

27


In [26]:
# accessing 2 D array elements
# imagine rows and columns
two_acc= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_acc)
print('second element in first row:',two_acc[0,1])
print("fifth element in second row:",two_acc[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
second element on first row: 2
fifth element in second row: 10


In [40]:
# accessing 3 D elements
three_acc=np.array([[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(three_acc)
print('find 15 in 3d array:',three_acc[0,1,1])
print('find 23 in 3d array:',three_acc[1,0,2])
print(three_acc[0])
print(three_acc[0,1])
print(three_acc[1])
print(three_acc[1,1])

[[[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
find 15 in 3d array: 15
find 23 in 3d array: 23
[[11 12 13]
 [14 15 16]]
[14 15 16]
[[21 22 23]
 [24 25 26]]
[24 25 26]


# slicing

In [65]:
#[start:end]  [start:end:steps]
sl=np.array([1,2,3,4,5,6,7,8,9])
print(sl[1:4])
print(sl[4:])
print(sl[:5])
print(sl[0:len(sl):2])
print(sl[0:5:2])

#negative slicing
print(sl[-3:-1])
print(sl[-4:])
 
# odd values
print(sl[::2])

# even values
print(sl[1::2])

[2 3 4]
[5 6 7 8 9]
[1 2 3 4 5]
[1 3 5 7 9]
[1 3 5]
[7 8]
[6 7 8 9]
[1 3 5 7 9]
[2 4 6 8]


In [76]:
# SLICING 2D ARRAY
two_sl=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_sl)
print(two_sl[1,1:4])
print(two_sl[0:2, 2]) #0:2 is for 2D array indexing
print(two_sl[0,1],two_sl[1,1]) #better to use way given below
print(two_sl[0:2,1]) # 0:2 is for 2D array indexing
print(two_sl[0:2, 1:4]) # 0:4 is for 2D array indexing and 1:4 is for within the each array indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
2 7
[2 7]
[[2 3 4]
 [7 8 9]]


# numpy data type
 - i for integer
 - b for boolean
 - u for unsigned integer
 - f for float
 - c for complex float
 - m for time delta
 - M for date time
 - O for object
 - S for string
 - U for unicode string
 - V for memory 

In [3]:
# checking data type of numpy array - dtype
chk=np.array([1,2,3,4])
print(chk.dtype)


int32


In [4]:
# string array
st=np.array(['apple','banana','orange'])
print(st.dtype)

<U6


In [6]:
# defining data type
intarr=np.array([1,2,3,4,5], dtype='S')
print(intarr)
print(intarr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [8]:
# array with 4 byte int
ba=np.array([1,2,3,4,5],dtype='i4')
print(ba)
print(ba.dtype)

[1 2 3 4 5]
int32


In [20]:
#converting float array to integer array
f=np.array([1.1,2.1,3.1,4.2,5.5])
f1=f.astype(int) #or astype('i')
print(f)
print(f1)
print(f1.dtype)

[1.1 2.1 3.1 4.2 5.5]
[1 2 3 4 5]
int32


In [18]:
#converting integer array to boolean
b=np.array([3,2,0,4,6,0,7])
b1=b.astype(bool)
print(b)
print(b1)
print(b1.dtype)

[3 2 0 4 6 0 7]
[ True  True False  True  True False  True]
bool


In [22]:
# copying array
c=np.array([1,2,3,4,5])
c1=c.copy()
c[0]=7 # modifying after copying doesnt change copied array elements
print(c)
print(c1)

[7 2 3 4 5]
[1 2 3 4 5]


In [25]:
# viewing array
v=np.array([1,2,3,4,5])
v1=v.view()
v[0]=7
print(v)
print(v1)

[7 2 3 4 5]
[7 2 3 4 5]


# Shape 

In [26]:
sh=np.array([[1,2,3,4], [5,6,7,8]])
print(sh.shape) #2dimensions and 4 elements

(2, 4)


In [30]:
sha=np.array([1,2,3,4], ndmin=5)
print(sha)
print(sha.ndim)
print(sha.shape)  

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


# reshaping element

In [3]:
# reshaping 1D to 2D
res=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
res1=res.reshape(4,3)
print(res)
print(res1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# reshaping 1D to 3D
resh1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
resh3=resh1.reshape(2,3,2)
print(resh1)
print(resh3)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
#return copy and view
s=np.array([1,2,3,4,5,6,7,8])
print(s.reshape(4,2))
print(s.reshape(2,4).base)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


In [14]:
# unknown dimension - you are allowed to have only one unknown dimension , pass -1
unkn=np.array([1,2,3,4,5,6,7,8])
unkn1=unkn.reshape(2,2,-1)
print(unkn1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
#FLATTENING of array by converting multidimensional into 1D
flt=np.array([[1,2,3],[4,5,6]])
flt1=flt.reshape(-1)
print(flt)
print(flt1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# ravel, rearranging the element, rot90, flip, fliplr, fliud (advance numpy)

In [20]:
# iteration in 1D
it1=np.array([1,2,3,4,5])
for i in it1:
    print(i)

1
2
3
4
5


In [23]:
# interation in 2D
it2=np.array([[1,2,3],[4,5,6]])
for i in it2:
    print(i)

[1 2 3]
[4 5 6]


In [24]:
it2=np.array([[1,2,3],[4,5,6]])
for i in it2:
    for j in i:
        print(j)

1
2
3
4
5
6


In [26]:
# iteration in 3D
it3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
for i in it3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
1
2
3
4
5
6


In [27]:
# iterating using nditer() 
nit3=np.array([[[1,2],[4,5]],[[2,3],[5,6]]])
for i in np.nditer(nit3):
    print(i)

1
2
4
5
2
3
5
6


In [8]:
# iteration with different step sizes
iter=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(iter[:, ::2]):  #iter[0:2, 0:3:2]
    print(i)


1
3
5
7


# joining array

In [11]:
#concatenate()
c1=np.array([1,2,3])
c2=np.array([4,5,6])
c=np.concatenate((c1,c2))
print(c)


[1 2 3 4 5 6]
