In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
type(x)

[1 2 3 4 5]


numpy.ndarray

In [4]:
# we can also pass a list, tuple or any array  like object with array() and it will be converted to ndarray
a= np.array((7,9,9,1,4,3))
print(a)

[7 9 9 1 4 3]


In [6]:
# dimensions in array - a dimension in array is one level of array depth(nested array)

# 0-D Array  -   scalars, are the elements in an array, each value in an array is a O-D array

# O-D array with value 42
y=np.array(42)
print(y)

42


In [7]:
#1-D array - an array that has 0-D arrays as its elements is uni directional or 1-D
one_d=np.array([11,12,13,14,15])
print(one_d)

[11 12 13 14 15]


In [9]:
# 2-D array
two_d=np.array([[1,2,3],[6,7,8]])
print(two_d)

[[1 2 3]
 [6 7 8]]


In [10]:
# 3-D array created with two 2-D array
three_d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(three_d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
print(a.ndim)
print(x.ndim)
print(y.ndim)
print(one_d.ndim)
print(two_d.ndim)
print(three_d.ndim)

1
1
0
1
2
3


In [12]:
# 5-D array conversion to 1 D 
five_d=np.array([1,2,3,4,5], ndmin=5)
print(five_d)
print("number of dimensions:", five_d.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


# indexing

In [19]:
# array indexing is same as accessing an array element 
# starts from 0 to n
ind=np.array([11,12,13,14])
print(ind[1],ind[2],ind[0])

12 13 11


In [17]:
# we can get element from adding them
ind=np.array([11,12,13,14])
print(ind[2]+ind[3])

27


In [26]:
# accessing 2 D array elements
# imagine rows and columns
two_acc= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_acc)
print('second element in first row:',two_acc[0,1])
print("fifth element in second row:",two_acc[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
second element on first row: 2
fifth element in second row: 10


In [40]:
# accessing 3 D elements
three_acc=np.array([[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(three_acc)
print('find 15 in 3d array:',three_acc[0,1,1])
print('find 23 in 3d array:',three_acc[1,0,2])
print(three_acc[0])
print(three_acc[0,1])
print(three_acc[1])
print(three_acc[1,1])

[[[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
find 15 in 3d array: 15
find 23 in 3d array: 23
[[11 12 13]
 [14 15 16]]
[14 15 16]
[[21 22 23]
 [24 25 26]]
[24 25 26]


# slicing

In [65]:
#[start:end]  [start:end:steps]
sl=np.array([1,2,3,4,5,6,7,8,9])
print(sl[1:4])
print(sl[4:])
print(sl[:5])
print(sl[0:len(sl):2])
print(sl[0:5:2])

#negative slicing
print(sl[-3:-1])
print(sl[-4:])
 
# odd values
print(sl[::2])

# even values
print(sl[1::2])

[2 3 4]
[5 6 7 8 9]
[1 2 3 4 5]
[1 3 5 7 9]
[1 3 5]
[7 8]
[6 7 8 9]
[1 3 5 7 9]
[2 4 6 8]


In [76]:
# SLICING 2D ARRAY
two_sl=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_sl)
print(two_sl[1,1:4])
print(two_sl[0:2, 2]) #0:2 is for 2D array indexing
print(two_sl[0,1],two_sl[1,1]) #better to use way given below
print(two_sl[0:2,1]) # 0:2 is for 2D array indexing
print(two_sl[0:2, 1:4]) # 0:4 is for 2D array indexing and 1:4 is for within the each array indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
2 7
[2 7]
[[2 3 4]
 [7 8 9]]
