In [24]:
import pandas as pd
import numpy as np


In [25]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"])
print(df)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [27]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [28]:
df.tail()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [29]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [30]:
df[['col1','col2']]

col1  col2
row1     0     1
row2     4     5
row3     8     9
row4    12    13
row5    16    17

In [31]:
df.loc[['row1','row2']]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

In [32]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [33]:
df.iloc[1:3,0:3]

col1  col2  col3
row2     4     5     6
row3     8     9    10

In [34]:
df.iloc[3:,1:3]

col2  col3
row4    13    14
row5    17    18

In [35]:
df.iloc[2:,2:]

col3  col4
row3    10    11
row4    14    15
row5    18    19

In [36]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [37]:
df[['col1','col4']]

col1  col4
row1     0     3
row2     4     7
row3     8    11
row4    12    15
row5    16    19

In [38]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [39]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [40]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=['row1','row2'],columns=['col1','col2','col3'])

In [41]:
df

col1  col2  col3
row1     1   NaN     2
row2     1   3.0     4

In [42]:
df.isnull().sum()

col1    0
col2    1
col3    0
dtype: int64

In [43]:
df['col3'].value_counts()

col3
2    1
4    1
Name: count, dtype: int64

In [44]:
df[df['col3']]

KeyError: "None of [Index([2, 4], dtype='int64')] are in the [columns]"

In [ ]:
df['col2'].unique()  

array([ 1,  5,  9, 13, 17])

In [ ]:
df>2

col1   col2   col3  col4
row1  False  False  False  True
row2   True   True   True  True
row3   True   True   True  True
row4   True   True   True  True
row5   True   True   True  True

In [1]:
df[df['col2']>2]

NameError: name 'df' is not defined